### PR TITLE
Theming from pals localization

### PR DESCRIPTION
**Pull request by erik-engstrom**
Fixes theming from pals #1727  localization errors

Summary:
This fixes identified localization errors in all language files (English, Spanish, German, Italian, French, Portuguese Brazilian and Chinese Simplified). 

@samvera/hyku-code-reviewers

### CODE REVIEW

**Review by labradford — COMMENTED** [review]
This looks good but we need to wait for PR https://github.com/labradford/hyku/pull/1 to be merged first. Then you will need to pull those changes back into this PR.

**Review by labradford — COMMENTED** [review]
Why did you make the changes from single quotes to double quotes?

**Comment by erik-engstrom** [comment]
> Why did you make the changes from single quotes to double quotes?
I don't think we added those double quotes, so not sure how that happened. I never saw any comments instructing us to do anything to the quotes.

**Comment by labradford** [comment]
> > Why did you make the changes from single quotes to double quotes?
> > I don't think we added those double quotes, so not sure how that happened. I never saw any comments instructing us to do anything to the quotes.

Can you change the double-quotes back to single-quotes? This is a really large PR so we don't want to add extra changes. It makes it harder for review. I suspect you ran rubocop -a on the file, but this file is in the rubocop ignore.

You can do this quickly with a find/replace

**Comment by erik-engstrom** [comment]
We'll get all the double quotes changed back to single quotes today. I agree, most likely was the rubocop -a that we ran to fix the white space errors that added the double quotes.

**Pull request merged**
